### ISSUE TITLE
parse_dependencies() cuts off column's src/dest filepath when using ".." as part of git_repo_path parameter

### ISSUE THREAD

**Issue by leilani-reich** [sailuh/kaiaulu#172]
This is a bug I mentioned here https://github.com/sailuh/kaiaulu/issues/168#issuecomment-1484031275.

## This is what the parsed dependencies table looks like:

src | dest | Call | Import | Use | Parameter | Contain | Create | Extend | Return | Implement | Cast | Throw | Annotation
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
/Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java | /Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/RestAdminApplication.java | 1 | 0 | 7 | 0 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 0
/Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java | /Users/xylent1/github/ics4zookeeper-api/src/main/java/org/apache/helix/zookeeper/zkclient/ZkClient.java | 2 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
 /Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java | /Users/xylent1/github/ics4zookeeper-api/src/main/java/org/apache/helix/zookeeper/impl/client/ZkClient.java | 2 | 1 | 10 | 0 | 2 | 2 | 0 | 0 | 0 | 0 | 0 | 0
 /Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java | /Users/xylent1/github/ics4zookeeper-api/src/main/java/org/apache/helix/zookeeper/datamodel/serializer/ZNRecordSerializer.java | 1 | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0
/Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java | /Users/xylent1/github/ics4zookeeper-api/src/main/java/org/apache/helix/zookeeper/datamodel/serializer/ByteArraySerializer.java | 1 | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0

I noticed that the parse_dependencies() function is giving me weird filepaths. For instance, looking at the example table above, I will show the first src filepath in the parsed depends table versus what was in the sdsm json (which I got from calling core:export-matrix on a dv8-sdsm file).

Parsed depends table src filepath:
```
/Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java
```
sdsm.json src filepath:
```
"/Users/xylent1/github/ics496/helix/helix-admin-webapp/src/main/java/org/apache/helix/webapp/HelixAdminWebApp.java"
```

So it looks like the filepath gets cut off in the depends table, "ics4" when it should be "ics496/helix/". I think this may be a bug, unless I'm doing something wrong.

**Comment by leilani-reich** [comment]
Hi Carlos,
For parse_dependencies(), I gave as a git_repo_path the path to the .git of a clone of the [Apache Helix](https://github.com/apache/helix) repo. The local path I made to this repo was "/Users/xylent1/github/ics496/helix".

I've linked the sdsm.json I used to check my actual filepath, as well as the depends table output.
[parse_dependencies.zip](https://github.com/sailuh/kaiaulu/files/11071091/parse_dependencies.zip)

**Comment by carlosparadis** [comment]
I just executed the `depends_showcase.Rmd` notebook using conf/helix.yml, but I am not being able to reproduce your error:

"/Users/cvp/Desktop/kaiaulu/rawdata/git_repo/helix/helix-rest/src/main/java/org/apache/helix/rest/server/service/ClusterService.java"

I suspect the issue lies on these lines, specifically the last one (note the comment above it):

https://github.com/sailuh/kaiaulu/blob/716a46e546d5293f3b2856cace62311c95aae977/R/parser.R#L547-L570

Could you tell me the content of your variables in this code block, if you execute the function step by step?

`folder_path` is actually not obtaining the full string of you path, resulting in the strange truncation. 

Your folder path should be `/Users/xylent1/github/ics496/helix` but I suspect it is being just `96/helix/`.

**Comment by leilani-reich** [comment]
Hi Carlos, upon closer inspection I believe the error may be due to how I was specifying my filepaths.

In particular, using this code with the ".." gives the weird filepaths:
```r
depends_path <-tool[["depends"]]
print(depends_path)
lang <- "java"
src_path <- "../helix/.git"
output_path <- "../dv8-project/"
parsed_depends_table <- parse_dependencies(depends_path, src_path, lang)
parsed_depends_table
```

Generates srcs and dests in this format:
```
/Users/xylent1/github/ics4helix-lock/src/main/java/org/apache/helix/lock/helix/ZKDistributedNonblockingLock
/Users/xylent1/github/ics4helix-admin-webapp/src/main/java/org/apache/helix/webapp/resources/ConfigResource.java
/Users/xylent1/github/ics4helixcore/src/test/java/org/apache/helix/integration/rebalancer/WagedRebalancer/TestWagedRebalanceFaultZone.java
```

<br class="Apple-interchange-newline">

Whereas using this code with "~" in beginning of filename:
```r
depends_path <-tool[["depends"]]
print(depends_path)
lang <- "java"
src_path <- "~/github/ics496/helix/.git"
output_path <- "~/github/ics496/dv8-project/"
parsed_depends_table <- parse_dependencies(depends_path, src_path, lang)
parsed_depends_table
```

Generates srcs and dests in this format:
```
helix-admin-webapp/src/main/java/org/apache/helix
zookeeper-api/src/main/java/org/apache/helix/zook
helix-admin-webapp/src/main/java/org/apache/helix
```

Does the format of the filepaths output by my second piece of code using the "~" look correct? So the parsed_dependencies() table should exclude the "/Users/xylent1/github/ics496/helix" from the path?


Also, are you expecting the user would not use ".." in the filepath as I had? Maybe we could clarify this by providing an example of how the git_repo_path should be formatted in the parameter description for git_repo_path.
https://github.com/sailuh/kaiaulu/blob/716a46e546d5293f3b2856cace62311c95aae977/R/parser.R#L541
So in this line we could add something like (ex. ~/project-path/.git). 

Unless we want to have functionality to account for if a user uses ".." in their filepath.

**Comment by carlosparadis** [comment]
> Does the format of the filepaths output by my second piece of code using the "~" look correct? So the parsed_dependencies() table should exclude the "/Users/xylent1/github/ics496/helix" from the path?

Yes, this is the intended behavior. Specifically, it should be converting filepaths from "Full" to "Relative". This is because in the long, long past (2014), long before Kaiaulu even existed in concept, we had this funny issue where everyone had a tool, and we would exchange data with collaborators, and we could not inner join anything as they kept adding the full path of everyone's computer..... so it is easier to just maintain in R memory relative filepaths. 

> Also, are you expecting the user would not use ".." in the filepath as I had? Maybe we could clarify this by providing an example of how the git_repo_path should be formatted in the parameter description for git_repo_path.

We should expect them to use that. This is a bug :( 

In the interest of time, use ~ to bypass the problem, and you can proceed with your milestones. 

I will try to replicate the issue with what you identified, and see if I can find a fix. But at the very least, this is no longer a blocker for you. 

In theory this would be the moment we would make a unit test out of this, and add to Kaiaulu so the test would fail until I could find a fix and make it future-proof. But doing so would lead to the issue of generating data on the fly again. I will give it more thought.

Nice finding 👍

**Comment by leilani-reich** [comment]
Got it. Thank you.

**Comment by carlosparadis** [comment]
@leilani-reich I pushed a fix for this on https://github.com/sailuh/kaiaulu/commit/851097eed2462c437535379fd82d71a101ecf771. Would you mind pulling the new code and trying on what initially led to the truncation of your data / loss of file paths?

Thanks!

**Comment by leilani-reich** [comment]
Hi Carlos, I tried out the code using the ".." in my git_repo_path parameter for parse_dependencies(), and my filepaths look good now. Thanks!

<img width="643" alt="Screenshot 2023-04-13 at 9 07 36 PM" src="https://user-images.githubusercontent.com/89750594/231969745-6f0f510e-3971-4656-8ff8-2f1423eaa1f4.png">

![image](https://user-images.githubusercontent.com/89750594/231969490-8da1a6b7-35ba-4a82-959a-f4705543521f.png)

**Comment by carlosparadis** [comment]
@leilani-reich Does the number of files between your new parse_dependencies() and DV8 match too? Or does that problem persist?

**Comment by leilani-reich** [comment]
Hi Carlos, the number of unique files (in variables list in the sdsm json) is my parse_dependencies is 1390, whereas in the DV8 Depends output it is 1416, so this problem still persists.

**Comment by leilani-reich** [comment]
Hi Carlos, the number of unique src/dest files in my new parse_dependencies is 1390, whereas in DV8 it is 1416, so this problem persists.

**Comment by carlosparadis** [comment]
I see. Okay, since these are separate problems, and the bug associated to this title is solved, let me close this and make a new issue off your information of the missing variables.
